Feature: take care of indent top & bottom
concordnow/ckeditor5-textindent pull request #7
Opened 2019-09-25 16:07 UTC by mostafa-sakhiri

https://contractlive.atlassian.net/browse/CPM-7000

2019-09-26 06:54 UTC, jeromelebaron commented on tests/horizontaltextindent.js
> +import Horizontaltextindent from './../src/horizontaltextindent';
```suggestion
import HorizontalTextIndent from './../src/horizontaltextindent';
```

2019-09-26 07:11 UTC, jeromelebaron requested changes
Un changement important

2019-09-26 07:11 UTC, jeromelebaron commented on tests/horizontaltextindent.js
> +		expect( Horizontaltextindent.pluginName ).to.equal( 'HorizontalTextIndent' );
```suggestion
		expect( HorizontalTextIndent.pluginName ).to.equal( 'HorizontalTextIndent' );
```

2019-09-26 10:07 UTC, mostafa-sakhiri commented on tests/horizontaltextindent.js
> +import Horizontaltextindent from './../src/horizontaltextindent';
Bien vu.

2019-09-26 10:07 UTC, mostafa-sakhiri commented on tests/horizontaltextindent.js
> +		expect( Horizontaltextindent.pluginName ).to.equal( 'HorizontalTextIndent' );
Bien vu.

2019-09-26 10:16 UTC, jeromelebaron commented
Ok for me

2019-09-26 10:16 UTC, jeromelebaron approved these changes

2019-09-26 12:23 UTC, ghost approved these changes

2019-09-26 15:01 UTC, thiberaw approved these changes

2019-09-30 08:07 UTC, jonathanpruvost approved these changes

2019-11-29 13:50 UTC, jeromelebaron commented
Merged with https://github.com/concordnow/ckeditor5-textindent/pull/15

2019-11-29 13:50 UTC, closed without merging